server:
  port: 9003

#eureka配置
eureka:
  instance:
    hostname: localhost9003
  client:
    register-with-eureka: false
    fetch-register: false
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/