
## spring配置
#spring:
#  application:
#    name: springcloud-server
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9003/eureka/
#    instance:
#      instance-id: springcloud-server-8001
##
#info:
#  app.name: springcloud-server-8001
#  company.name: xinduan
#
