server:
  port: 9001

#eureka配置
eureka:
  instance:
    hostname: localhost9002
  client:
    register-with-eureka: false
    fetch-register: false
    service-url:
      defaultZone: http://localhost:9002/eureka/,http://localhost:9003/eureka/