server:
  port: 9002

#eureka配置
eureka:
  instance:
    hostname: localhost9002
  client:
    register-with-eureka: false
    fetch-register: false
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9003/eureka/